"""Add ApprovalHistory table

Revision ID: db7fc850e3f7
Revises: 7a26957c1efd
Create Date: 2024-11-11 22:15:11.280625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7fc850e3f7'
down_revision = '7a26957c1efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.approval_id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_history')
    # ### end Alembic commands ###
